enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[com.duolingo]
apkmirror-dlurl = "https://www.apkmirror.com/wp-content/themes/APKMirror/download.php?id=11246627&key=9e7eadd13e63edd247095f82d9848201003b9b6f"
build-mode = "module"
pkg = "com.duolingo"
